### GET request to example server
GET localhost:8080/user


### Create user
POST http://localhost:8080/user
Content-Type: application/json

{
  "first_name": "timofei",
  "last_name": "arefev",
  "login": "test",
  "password": "test"
}

### GET user by id
GET http://localhost:8080/user/1


### DELETE user
#DELETE localhost:8080/user/1

### Update user
PUT localhost:8080/user/5
Content-Type: application/json

{
  "first_name": "Not timofei",
  "last_name": "Arefev",
  "login": "test",
  "password": "test"
}

### Chat

### Create chat
POST localhost:8080/chat
Content-Type: application/json

{
  "name": "chat1"
}



### Role

### Create role
POST localhost:8080/role
Content-Type: application/json

{
  "name": "admin"
}





### Get members
GET localhost:8080/member

### Create member
POST http://localhost:8080/member
Content-Type: application/json

{
  "user_id": 1,
  "chat_id": 1
}


### Scheduled task

### Get scheduled task
GET localhost:8080/scheduled-task

### Create scheduled task


### Chat

### Get chat
GET localhost:8080/chat

###  Strike

### Get strike
GET localhost:8080/strike

### User

### Get user
GET localhost:8080/user


### Member

### Get member
GET localhost:8080/member
